#+title: Miniline - Modular status bar in echo area

The echo area is unused most of the time.  Sometimes this empty area so
annoying that some people want to get rid of it.  This package makes it
useful by showing a status bar in it when it's unused.  This is especially
helpful when you use Emacs as your X window manager using EXWM.

* Installation

** Quelpa

#+begin_src emacs-lisp
(quelpa '(miniline :fetcher git
                   :url "https://codeberg.org/akib/emacs-miniline.git"))
#+end_src

** Straight.el

#+begin_src emacs-lisp
(straight-use-package
 '(miniline :type git
            :repo "https://codeberg.org/akib/emacs-miniline.git"))
#+end_src

** Manual

First install =minibuffer-line= package from ELPA.  Then download
=miniline.el= and put it in your ~load-path~.

* Usage

Enable ~miniline-mode~ to display miniline.  You may want to put
~(miniline-mode +1)~ in your init file.  There are several user options you
can customize, use ~customize-group~ to see and possibly customize them.

Miniline renders the status bar and it uses =minibuffer-line= package to
show the line in echo area.  To change the refresh rate, customize the
~minibuffer-line-refresh-interval~ variable.  To change the face, customize
the ~minibuffer-line~ face.
